apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: task-manager
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGRiOjU0MzIvdGFza19tYW5hZ2Vy  # base64 encoded