# kubernetes/backend/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: task-manager
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGRiLnRhc2stbWFuYWdlci5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3Rhc2tfbWFuYWdlcg==