apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: task-manager
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend
  type: ClusterIP